### ISSUE TITLE
Somehow cannot be installed

### ISSUE THREAD

**Issue by Juniperus1873** [upday7/WebQuery#4]
Somehow cannot be installed. An error occurred every time when restarting Anki:

Traceback (most recent call last):
  File "aqt/progress.pyc", line 69, in handler
  File "aqt/main.pyc", line 110, in setupProfile
  File "aqt/main.pyc", line 244, in loadProfile
  File "anki/hooks.pyc", line 26, in runHook
  File "/Users/Daoyuan/Library/Application Support/Anki2/addons/webquery.py", line 27, in start
    import WebQuery
  File "/Users/Daoyuan/Library/Application Support/Anki2/addons/WebQuery/__init__.py", line 12, in <module>
    from uuid import uuid4
ImportError: No module named uuid

**Comment by upday7** [comment]
Hi  @Juniperus1873 Please try to download from here i just place a fix: [](https://github.com/upday7/WebQuery/tree/master/2.0), please let me know if this works.

**Comment by Juniperus1873** [comment]
it's works now! it's truly a helpful extension!
