### ISSUE TITLE
error message anki beta 2.1 beta 13

### ISSUE THREAD

**Issue by jandoor** [upday7/WebQuery#6]
When loading 'Web_Query':
Traceback (most recent call last):
  File "aqt/addons.py", line 58, in loadAddons
  File "/Users/macwerk/Library/Application Support/Anki2/addons21/627484806/__init__.py", line 84, in <module>
    class _Vars(metaclass=_MetaEasyVar):
  File "/Users/macwerk/Library/Application Support/Anki2/addons21/627484806/__init__.py", line 86, in _Vars
    addons_folder = mw.addonManager.addonsFolder()
AttributeError: 'AnkiQt' object has no attribute 'addonManager'
 
]

**Comment by upday7** [comment]
@jandoor .. hmm actually im using the latest beta version .. will you have a try?

**Comment by jandoor** [comment]
Oke i'm an idiot.
I thought this was the last beta version.
I'm sorry haha.
Btw you are awesome for developing this addon!
